// <auto-generated />
namespace Supratentorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Nullableemaildatearchived : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullableemaildatearchived));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010528137_Nullable email date archived"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
