// <auto-generated />
namespace Supratentorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class StaffPropertiesMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StaffPropertiesMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201506181129440_Staff Properties Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
