// <auto-generated />
namespace Supratentorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Removedstaffproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedstaffproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201506290356311_Removed staff properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
